baseURL = 'https://chienhsiang-hung.github.io/blog'
languageCode = 'en-us'
title = 'Hung, Chien-Hsiang | Blog'
theme = "loveit" 

[params]
  [params.home]
    [params.home.profile]
      avatarURL = "https://chienhsiang-hung.github.io/my_beautiful-jekyll/assets/img/avatar-icon.png"